M48
; DRILL file {KiCad 8.0.6} date 2024-11-22T14:42:41+0900
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-22T14:42:41+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0118
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0276
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T5C0.0394
%
G90
G05
T1
X5.5Y-3.6
X5.6Y-3.7
T2
X5.1Y-2.8
X5.1Y-3.1
X5.3Y-2.8
X5.3Y-3.1
X5.7Y-2.8
X5.7Y-3.1
X5.9Y-2.8
X5.9Y-3.1
T3
X5.2Y-3.7
X5.2Y-3.8
X5.2Y-3.9
X5.2213Y-3.4
X5.3Y-3.4
X5.7213Y-3.4
X5.8Y-3.4
X5.9Y-3.7
X5.9Y-3.8
X5.9Y-3.9
T4
X5.1Y-2.4
X5.1Y-2.5
X5.9Y-2.4
X5.9Y-2.5
T5
X4.7Y-3.1
X4.7Y-3.2
X4.7Y-3.3
X4.7Y-3.4
M30
